services:
  discovery:
    image: discovery:latest
    mem_limit: 512m
    ports:
      - "8080:8080"
  sales:
    build: sales
    mem_limit: 512m
    ports:
      - "8080:8081"
    environment:
      - EUREKA_URI=http://discovery:8080/eureka
  postgres:
    image: postgres:11.21-bullseye
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Admin123$