server:
  port: 0
spring:
  application:
    name: inventory
  datasource:
    url:  jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: Admin123$
    driver-class-name:  oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    database-platform:  org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
  instance:
    instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
    prefer-ip-address: true
