server:
  port: 9090
spring:
  datasource:
    url:  jdbc:oracle:thin:@//localhost:1521/xe
    username: SYSTEM
    password: Admin123$
    driver-class-name:  oracle.jdbc.OracleDriver
  jpa:
    database-platform:  org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: update
    show-sql: true