server:
    port: 8080
spring:
    application:
            name: sales
    datasource:
        url:  jdbc:postgresql://postgres:5432/postgres
        username: postgres
        password: Admin123$
        driver-class-name:  org.postgresql.Driver
    jpa:
        database-platform:  org.hibernate.dialect.OracleDialect
        hibernate.ddl-auto: update
        show-sql: true
eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URI:http://localhost:8080/eureka}
    instance:
        instance-id: ${spring.application.name}:${INSTANCE_ID:${random.value}}
        prefer-ip-address: true
resilience4j:
    circuitbreaker:
        instances:
            inventory:
                failureRateThreshold: 50
                automaticTransitionFromOpenToHalfOpenEnabled: true
                waitDurationInOpenState: 10s
                slidingWindowType: COUNT_BASED
                slidingWindowSize: 2
                minimumNumberOfCalls: 1
management:
    endpoints:
        web:
            exposure:
                include: "*"
        health:
            enabled: true
            show-details: always
    health:
        circuitbreakers:
            enabled: true
